/*
 * This source file was generated by the Gradle 'init' task
 */
package com.frontierfortress;

import com.frontierfortress.window.CreateWindow;

public class App {
    public String getGreeting() {
        return "Hello World!";
    }

    public static void main(String[] args) {
        new CreateWindow(720, 1280).run();
    }
}
